# Default values for pdf.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 118504922878.dkr.ecr.us-east-1.amazonaws.com/cloudnative/soc_pdf_tomcat
  tag: 0.2.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8083

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: pdf
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - pdf
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - pdf

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
